using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SolTake.Domain.TopicAggregate.Entities;

namespace SolTake.Infrastructure.Seeds
{
    public class Topics_Seed : IEntityTypeConfiguration<Topic>
    {
        public void Configure(EntityTypeBuilder<Topic> builder)
        {
            builder
                .HasData(
                    [
                        //matematik
                        //kpss tyt ayt
                        new { Id = 1, Name = "Matematik Temel Kavramlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2, Name = "Sayılar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3, Name = "Sayı Basamakları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 4, Name = "Sayı Kümeleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5, Name = "Doğal Sayılar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6, Name = "Tam Sayılar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7, Name = "Ondalık Sayılar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8, Name = "Sayma Sistemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9, Name = "Bölme", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10, Name = "Bölünebilme Kuralları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 11, Name = "EBOB – EKOK", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 12, Name = "Asal Çarpanlara Ayırma", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 13, Name = "Denklemler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 14, Name = "Rasyonel Sayılar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 15, Name = "Kesir ve Kesir Türleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 16, Name = "Rasyonel Sayılarda Dört İşlem", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17, Name = "Basit Eşitsizlikler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 18, Name = "Mutlak Değer", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 19, Name = "Üslü Sayılar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 20, Name = "Köklü Sayılar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 21, Name = "Çarpanlara Ayırma", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 22, Name = "Oran Orantı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 23, Name = "Denklem Çözme", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 24, Name = "Problemler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 25, Name = "Sayı Problemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 26, Name = "Denklem Kurma Problemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 27, Name = "Kesir Problemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 28, Name = "Yaş Problemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 29, Name = "Havuz Problemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 30, Name = "Hareket Hız Problemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 31, Name = "İşçi Emek Problemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 32, Name = "Yüzde Problemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 33, Name = "Kar Zarar Problemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 34, Name = "Karışım Problemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 35, Name = "Grafik Problemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 36, Name = "Rutin Olmayan Problemler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 37, Name = "Kümeler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 38, Name = "Kartezyen Çarpım", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 39, Name = "İşlem - Modüler Aritmetik", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 40, Name = "Bağıntı ve Fonksiyon", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 41, Name = "Faktöriyel", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 42, Name = "Permütasyon", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 43, Name = "Kombinasyon", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 44, Name = "Olasılık", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 45, Name = "Tablo ve Grafikler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 46, Name = "Tablo ve Yorumlama", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 47, Name = "Grafik ve Yorumlama", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 48, Name = "Sayısal Mantık", CreatedAt = new DateTime(2025,6,9) },
                        //tyt ayt
                        new { Id = 49, Name = "Mantık", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 50, Name = "Fonskiyonlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 51, Name = "Polinomlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 52, Name = "2.Dereceden Denklemler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 53, Name = "Veri – İstatistik", CreatedAt = new DateTime(2025,6,9) },
                        //ayt
                        new { Id = 54, Name = "Karmaşık Sayılar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 55, Name = "2.Dereceden Eşitsizlikler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 56, Name = "Parabol", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 57, Name = "Trigonometri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 58, Name = "Logaritma", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 59, Name = "Diziler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 60, Name = "Limit", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 61, Name = "Türev", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 62, Name = "İntegral", CreatedAt = new DateTime(2025,6,9) },
                        //lgs
                        new { Id = 63, Name = "Çarpanlar ve Katlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 64, Name = "Üslü İfadeler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 65, Name = "Kareköklü İfadeler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 66, Name = "Veri Analizi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 67, Name = "Basit Olayların Olma Olasılığı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 68, Name = "Cebirsel İfadeler ve Özdeşlikler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 69, Name = "Doğrusal Denklemler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 70, Name = "Eşitsizlikler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 71, Name = "Üçgenler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 72, Name = "Eşlik ve Benzerlik", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 73, Name = "Geometrik Cisimler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 74, Name = "Dönüşüm Geometrisi", CreatedAt = new DateTime(2025,6,9) },

                        //Biyoloji
                        new { Id = 1001, Name = "Canlıların Ortak Özellikleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1002, Name = "Canlıların Temel Bileşenleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1003, Name = "Hücre ve Organeller – Madde Geçişleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1004, Name = "Canlıların Sınıflandırılması", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1005, Name = "Hücrede Bölünme – Üreme", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1006, Name = "Kalıtım", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1007, Name = "Bitki Biyolojisi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1008, Name = "Ekosistem", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1009, Name = "Sinir Sistemi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1010, Name = "Endokrin Sistem ve Hormonlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1011, Name = "Duyu Organları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1012, Name = "Destek ve Hareket Sistemi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1013, Name = "Sindirim Sistemi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1014, Name = "Dolaşım ve Bağışıklık Sistemi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1015, Name = "Solunum Sistemi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1016, Name = "Boşaltım Sistemi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1017, Name = "Üreme Sistemi ve Embriyonik Gelişim", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1018, Name = "Komünite Ekolojisi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1019, Name = "Popülasyon Ekolojisi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1020, Name = "Genden Proteine", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1021, Name = "Nükleik Asitler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1022, Name = "Genetik Şifre ve Protein Sentezi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1023, Name = "Canlılarda Enerji Dönüşümleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1024, Name = "Canlılık ve Enerji", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1025, Name = "Fotosentez", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1026, Name = "Kemosentez", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1027, Name = "Hücresel Solunum", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1028, Name = "Bitki Biyolojisi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 1029, Name = "Canlılar ve Çevre", CreatedAt = new DateTime(2025,6,9) },

                        //Cografya
                        //kpass
                        new { Id = 2001, Name = "Türkiye'nin Coğrafi Konumu", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2002, Name = "Türkiye'nin Coğrafi Konumu - Matematik (Mutlak) Konum", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2003, Name = "Türkiye'nin Coğrafi Konumu - Türkiye'nin Matematik (Mutlak) Konumu ve Sonuçları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2004, Name = "Türkiye'nin Coğrafi Konumu - Türkiye'nin Özel (Göreceli) Konumu ve Sonuçları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2005, Name = "Türkiye'nin Coğrafi Konumu - Türkiye'nin Jeopolitiği", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2006, Name = "Türkiye'nin Yerşekilleri ve Özellikleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2007, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'nin Yerşekillerinin Genel Özellikleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2008, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Fiziki Haritalar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2009, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'nin Jeolojik Geçmişi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2010, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'nin Platoları ve Ovaları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2011, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'de Dış Güçlerin Oluşturduğu Yer Şekilleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2012, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'nin Kıyı Tipleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2013, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'de Toprak Oluşumu ve Tipleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2014, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'nin Su Varlığı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2015, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'de Doğal Afetler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2016, Name = "Türkiye'nin İklimi ve Bitki Örtüsü", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2017, Name = "Türkiye'nin İklimi ve Bitki Örtüsü - Türkiye'nin İklimi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2018, Name = "Türkiye'nin İklimi ve Bitki Örtüsü - Türkiye'de Sıcaklık", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2019, Name = "Türkiye'nin İklimi ve Bitki Örtüsü - Türkiye'de Nemlilik ve Yağış", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2020, Name = "Türkiye'nin İklimi ve Bitki Örtüsü - Türkiye'de İklim Tipleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2021, Name = "Türkiye'nin İklimi ve Bitki Örtüsü - Türkiye'nin Bitki Örtüsü", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2022, Name = "Türkiye'nin İklimi ve Bitki Örtüsü - Türkiye'nin İklim Tipleri ve Bitki Örtüsü", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2023, Name = "Türkiye'de Nüfus ve Yerleşme", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2024, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'de Nüfus Özellikleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2025, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'de Nüfusun Dağılışı ve Nüfus Yoğunluğu", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2026, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'nin Nüfusu ve Nüfus Sayımları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2027, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'nin Nüfus Politikaları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2028, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'de Nüfus Projeksiyonları: Türkiye Nüfusunun Geleceği", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2029, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'de Göçler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2030, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'de Yerleşme", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2031, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'de Mesken Tipleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2032, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2033, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık - Anadolu Uygarlıkları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2034, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık - Türkiye'de Arazi Kullanımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2035, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık - Türkiye Ekonomisinin Sektörel Dağılımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2036, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık - Türkiye Ekonomisini Etkileyen Faktörler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2037, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık - Türkiye'de Tarım", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2038, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık - Türkiye'de Hayvancılık", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2039, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık - Türkiye'de Ormancılık", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2040, Name = "Türkiye'de Madenler, Enerji Kaynakları ve Sanayi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2041, Name = "Türkiye'de Madenler, Enerji Kaynakları ve Sanayi - Türkiye'de Madenler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2042, Name = "Türkiye'de Madenler, Enerji Kaynakları ve Sanayi - Türkiye'de Enerji Kaynakları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2043, Name = "Türkiye'de Madenler, Enerji Kaynakları ve Sanayi - Türkiye'de Sanayi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2044, Name = "Türkiye'de Ulaşım, Ticaret ve Turizm", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2045, Name = "Türkiye'de Ulaşım, Ticaret ve Turizm - Türkiye'de Ulaşım", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2046, Name = "Türkiye'de Ulaşım, Ticaret ve Turizm - Türkiye'de Ticaret", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2047, Name = "Türkiye'de Ulaşım, Ticaret ve Turizm - Türkiye'de Turizm", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2048, Name = "Türkiye'de Ulaşım, Ticaret ve Turizm - Türkiye'nin Millî Parkları Türkiye’de Şehirler ve Özellikleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2049, Name = "Türkiye'nin Coğrafi Bölgeleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2050, Name = "Türkiye'nin Coğrafi Bölgeleri - Türkiye'de Bölge Sınıflandırması", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2051, Name = "Türkiye'nin Coğrafi Bölgeleri - Türkiye'nin Bölgesel Kalkınma Projeleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2052, Name = "Türkiye'nin Coğrafi Bölgeleri - Türkiye'nin Coğrafi Bölgeleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2053, Name = "Türkiye'nin Coğrafi Bölgeleri - Karadeniz Bölgesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2054, Name = "Türkiye'nin Coğrafi Bölgeleri - Marmara Bölgesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2055, Name = "Türkiye'nin Coğrafi Bölgeleri - Ege Bölgesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2056, Name = "Türkiye'nin Coğrafi Bölgeleri - Akdeniz Bölgesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2057, Name = "Türkiye'nin Coğrafi Bölgeleri - İç Anadolu Bölgesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2058, Name = "Türkiye'nin Coğrafi Bölgeleri - Doğu Anadolu Bölgesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2059, Name = "Türkiye'nin Coğrafi Bölgeleri - Güneydoğu Anadolu Bölgesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2060, Name = "Türkiye'nin Coğrafi Bölgeleri - Bölgelerin Özelliklerinin Karşılaştırılması", CreatedAt = new DateTime(2025,6,9) },
                        //tyt
                        new { Id = 2061, Name = "Doğa ve İnsan", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2062, Name = "Dünya’nın Şekli ve Hareketleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2063, Name = "Coğrafi Konum", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2064, Name = "Harita Bilgisi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2065, Name = "Atmosfer ve Sıcaklık", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2066, Name = "İklimler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2067, Name = "Basınç ve Rüzgarlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2068, Name = "Nem, Yağış ve Buharlaşma", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2069, Name = "İç Kuvvetler / Dış Kuvvetler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2070, Name = "Su – Toprak ve Bitkiler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2071, Name = "Nüfus", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2072, Name = "Göç", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2073, Name = "Yerleşme", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2074, Name = "Türkiye’nin Yer Şekilleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2075, Name = "Ekonomik Faaliyetler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2076, Name = "Bölgeler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2077, Name = "Uluslararası Ulaşım Hatları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2078, Name = "Çevre ve Toplum", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2079, Name = "Doğal Afetler", CreatedAt = new DateTime(2025,6,9) },
                        //ayt
                        new { Id = 2080, Name = "Ekosistem", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2081, Name = "Biyoçeşitlilik", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2082, Name = "Biyomlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2083, Name = "Ekosistemin Unsurları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2084, Name = "Enerji Akışı ve Madde Döngüsü", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2085, Name = "Ekstrem Doğa Olayları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2086, Name = "Küresel İklim Değişimi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2087, Name = "Nüfus Politikaları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2088, Name = "Türkiye'de Nüfus ve Yerleşme", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2089, Name = "Ekonomik Faaliyetler ve Doğal Kaynaklar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2090, Name = "Göç ve Şehirleşme", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2091, Name = "Türkiye Ekonomisi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2092, Name = "Türkiye'nin Ekonomi Politikaları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2093, Name = "Türkiye Ekonomisinin Sektörel Dağılımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2094, Name = "Türkiye'de Tarım", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2095, Name = "Türkiye'de Hayvancılık", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2096, Name = "Türkiye'de Madenler ve Enerji Kaynakları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2097, Name = "Türkiye'de Sanayi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2098, Name = "Türkiye'de Ulaşım", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2099, Name = "Türkiye'de Ticaret ve Turizm", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2100, Name = "Geçmişten Geleceğe Şehir ve Ekonomi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2101, Name = "Türkiye'nin İşlevsel Bölgeleri ve Kalkınma Projeleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2102, Name = "Hizmet Sektörünün Ekonomideki Yeri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2103, Name = "Küresel Ticaret", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2104, Name = "Bölgeler ve Ülkeler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2105, Name = "İlk Uygarlıklar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2106, Name = "Kültür Bölgeleri ve Türk Kültürü", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2107, Name = "Sanayileşme Süreci: Almanya", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2108, Name = "Tarım ve Ekonomi İlişkisi Fransa – Somali", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2109, Name = "Ülkeler Arası Etkileşim", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2110, Name = "Jeopolitik Konum", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2111, Name = "Çatışma Bölgeleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2112, Name = "Küresel ve Bölgesel Örgütler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2113, Name = "Çevre ve Toplum", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2114, Name = "Çevre Sorunları ve Türleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2115, Name = "Madenler ve Enerji Kaynaklarının Çevreye Etkisi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2116, Name = "Doğal Kaynakların Sürdürülebilir Kullanımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2117, Name = "Ekolojik Ayak İzi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2118, Name = "Doğal Çevrenin Sınırlılığı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2119, Name = "Çevre Politikaları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2120, Name = "Çevresel Örgütler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2121, Name = "Çevre Anlaşmaları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 2122, Name = "Doğal Afetler", CreatedAt = new DateTime(2025,6,9) },
                        
                        //din kulturu
                        new { Id = 3001, Name = "İnanç", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3002, Name = "İbadet", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3003, Name = "Ahlak ve Değerler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3004, Name = "Din, Kültür ve Medniyet", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3005, Name = "Hz. Mhammed (S.A.V.)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3006, Name = "Vahiy ve Akıl", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3007, Name = "Dünya ve Ahiret", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3008, Name = "Kur'an'a göre Hz. Muhammed (S.A.V.)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3009, Name = "İnançla İlgili Meseleler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3010, Name = "Yahudilik ve Hristiyanlık", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3011, Name = "İslam ve Bilim", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3012, Name = "Anadolu da İslam", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3013, Name = "İslam Düşüncesinde Tasavvufi Yorumlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3014, Name = "Güncel Dini Meseler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3015, Name = "Hint ve Çin Dinleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3016, Name = "Kur'an'da Bazı Kavramlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3017, Name = "Kader İnancı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3018, Name = "Zekat ve Sadaka", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3019, Name = "Din ve Hayat", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3020, Name = "Hz. Muhammed'in Örnekliği", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 3021, Name = "Kur'an-ı Kerim ve Özellikleri", CreatedAt = new DateTime(2025,6,9) },

                        //felsefe
                        new { Id = 4001, Name = "Felsefenin Konusu", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 4002, Name = "Bilgi Felsefesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 4003, Name = "Varlık Felsefesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 4004, Name = "Din, Kültür ve Medniyet", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 4005, Name = "Ahlak Felsefesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 4006, Name = "Sanat Felsefesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 4007, Name = "Din Felsefesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 4008, Name = "Siyaset Felsefesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 4009, Name = "Bilim Felsefesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 4010, Name = "İlk Çağ Felsefesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 4011, Name = "MÖ 6. Yüzyıl – MS 2. Yüzyıl Felsefesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 4012, Name = "MS 2. Yüzyıl – MS 15. Yüzyıl Felsefesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 4013, Name = "15. Yüzyıl – 17. Yüzyıl Felsefesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 4014, Name = "18. Yüzyıl – 19. Yüzyıl Felsefesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 4015, Name = "20. Yüzyıl Felsefesi", CreatedAt = new DateTime(2025,6,9) },


                        //fizik
                        new { Id = 5001, Name = "Fizik Bilimine Giriş", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5002, Name = "Madde Ve Özellikleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5003, Name = "Kaldırma Kuvveti", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5004, Name = "Basınç", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5005, Name = "Isı, Sıcaklık ve Genleşme", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5006, Name = "Hareket ve Kuvvet", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5007, Name = "Dinamik", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5008, Name = "İş, Güç ve Enerji", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5009, Name = "Elektrostatik", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5010, Name = "Elektrik Akımı ve Devreler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5011, Name = "Elektriksel Enerji ve Güç", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5012, Name = "Optik", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5013, Name = "Manyetizma", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5014, Name = "Dalgalar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5015, Name = "Vektörler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5016, Name = "Kuvvet, Tork ve Denge", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5017, Name = "Kütle Merkezi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5018, Name = "Basit Makineler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5019, Name = "Hareket", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5020, Name = "Newton’un Hareket Yasaları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5021, Name = "İş, Güç ve Enerji II", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5022, Name = "Atışlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5023, Name = "İtme ve Momentum", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5024, Name = "Elektrik Alan ve Potansiyel", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5025, Name = "Paralel Levhalar ve Sığa", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5026, Name = "Manyetik Alan ve Manyetik Kuvvet", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5027, Name = "İndüksiyon, Alternatif Akım ve Transformatörler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5028, Name = "Çembersel Hareket", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5029, Name = "Dönme, Yuvarlanma ve Açısal Momentum", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5030, Name = "Kütle Çekim ve Kepler Yasaları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5031, Name = "Basit Harmonik Hareket", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5032, Name = "Dalga Mekaniği ve Elektromanyetik Dalgalar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5033, Name = "Atom Modelleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5034, Name = "Büyük Patlama ve Parçacık Fiziği", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5035, Name = "Radyoaktivite", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5036, Name = "Özel Görelilik", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5037, Name = "Kara Cisim Işıması", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5038, Name = "Fotoelektrik Olay ve Compton Olayı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 5039, Name = "Modern Fiziğin Teknolojideki Uygulamaları", CreatedAt = new DateTime(2025,6,9) },

                        //geometri
                        new { Id = 6001, Name = "Geometrik Kavramlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6002, Name = "Doğruda Açılar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6003, Name = "Üçgende Açılar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6004, Name = "Üçgende Eşlik ve Benzerlik", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6005, Name = "Özel Üçgenler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6006, Name = "Dik Üçgen", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6007, Name = "İkizkenar Üçgen", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6008, Name = "Eşkenar Üçgen", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6009, Name = "Açıortay", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6010, Name = "Kenarortay", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6011, Name = "Eşlik ve Benzerlik", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6012, Name = "Üçgende Alan", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6013, Name = "Üçgende Benzerlik", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6014, Name = "Üçgende Açı Kenar Bağıntıları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6015, Name = "Çokgenler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6016, Name = "Özel Dörtgenler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6017, Name = "Dörtgenler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6018, Name = "Deltoid", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6019, Name = "Paralelkenar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6020, Name = "Eşkenar Dörtgen", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6021, Name = "Dikdörtgen", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6022, Name = "Kare", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6023, Name = "Yamuk", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6024, Name = "Çember ve Daire", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6025, Name = "Çemberde Açı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6026, Name = "Çemberde Uzunluk", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6027, Name = "Dairede Çevre ve Alan", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6028, Name = "Analitik Geometri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6029, Name = "Noktanın Anzalitiği", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6030, Name = "Analitik Düzlem", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6031, Name = "Doğrunun Grafiğinin Çizimi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6032, Name = "Doğrunun Denklemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6033, Name = "Doğrunun Analitiği", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6034, Name = "Simetriler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6035, Name = "Eşitsizlikler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6036, Name = "Dönüşüm Geometrisi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6037, Name = "Katı Cisimler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6038, Name = "Prizmalar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6039, Name = "Dikdörtgenler Prizmalar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6040, Name = "Küp", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6041, Name = "Silindir", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6042, Name = "Dönel Silindir", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6043, Name = "Kesik Piramit", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6044, Name = "Piramit", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6045, Name = "Koni", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6046, Name = "Küre", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 6047, Name = "Çemberin Analitiği", CreatedAt = new DateTime(2025,6,9) },

                        //kimya
                        new { Id = 7001, Name = "Kimya Bilimi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7002, Name = "Atom ve Yapısı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7003, Name = "Periyodik Sistem", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7004, Name = "Kimyasal Türler Arası Etkileşimler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7005, Name = "Maddenin Halleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7006, Name = "Kimyanın Temel Kanunları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7007, Name = "Asitler, Bazlar ve Tuzlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7008, Name = "Kimyasal Hesaplamalar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7009, Name = "Karışımlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7010, Name = "Endüstride ve Canlılarda Enerji", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7011, Name = "Kimya Her Yerde", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7012, Name = "Modern Atom Teorisi.", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7013, Name = "Gazlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7014, Name = "Sıvı Çözeltiler ve Çözünürlük.", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7015, Name = "Kimyasal Tepkimelerde Enerji", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7016, Name = "Kimyasal Tepkimelerde Hız", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7017, Name = "Kimyasal Tepkimelerde Denge", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7018, Name = "Asit-Baz Dengesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7019, Name = "Çözünürlük Dengesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7020, Name = "Kimya ve Elektrik", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7021, Name = "Organik Kimyaya Giriş", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7022, Name = "Organik Kimya", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7023, Name = "Hidrokarbonlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7024, Name = "Fonksiyonel Gruplar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 7025, Name = "Enerji Kaynakları ve Bilimsel Gelişmeler", CreatedAt = new DateTime(2025,6,9) },

                        //tarih
                        //kpss
                        new { Id = 8001, Name = "İslamiyet Öncesi Türk Tarihi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8002, Name = "İlk Türk - İslam Devletleri ve Beylikleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8003, Name = "Osmanlı Devleti Kuruluş ve Yükselme Dönemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8004, Name = "Osmanlı Devleti’nde Kültür ve Uygarlık", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8005, Name = "XVII. Yüzyılda Osmanlı Devleti (Duraklama Dönemi)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8006, Name = "XVIII. Yüzyılda Osmanlı Devleti (Gerileme Dönemi)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8007, Name = "XIX. Yüzyılda Osmanlı Devleti (Dağılma Dönemi)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8008, Name = "XX. Yüzyılda Osmanlı Devleti", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8009, Name = "Kurtuluş Savaşı Hazırlık Dönemi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8010, Name = "I. TBMM Dönemi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8011, Name = "Kurtuluş Savaşı Muharebeler Dönemi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8012, Name = "Atatürk İnkılapları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8013, Name = "Atatürk İlkeleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8014, Name = "Partiler ve Partileşme Dönemi (İç Politika)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8015, Name = "Atatürk Dönemi Türk Dış Politikası", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8016, Name = "Atatürk Sonrası Dönem", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8017, Name = "Atatürk’ün Hayatı ve Kişiliği", CreatedAt = new DateTime(2025,6,9) },
                        //tyt + ayt
                        new { Id = 8018, Name = "Tarih ve Zaman", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8019, Name = "İnsanlığın İlk Dönemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8020, Name = "Ortaçağ’da Dünya", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8021, Name = "İlk ve Orta Çağlarda Türk Dünyası", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8022, Name = "İslam Medeniyetinin Doğuşu", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8023, Name = "Türklerin İslamiyet’i Kabulü ve İlk Türk İslam Devletleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8024, Name = "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8025, Name = "Beylikten Devlete Osmanlı Siyaseti", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8026, Name = "Devletleşme Sürecinde Savaşçılar ve Askerler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8027, Name = "Dünya Gücü Osmanlı Devleti", CreatedAt = new DateTime(2025,6,9) },
                        //tyt
                        new { Id = 8028, Name = "Yeni Çağ Avrupa Tarihi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8029, Name = "Yakın Çağ Avrupa Tarihi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8030, Name = "Osmanlı Devletinde Arayış Yılları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8031, Name = "18. Yüzyılda Değişim ve Diplomasi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8032, Name = "En Uzun Yüzyıl", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8033, Name = "Osmanlı Kültür ve Medeniyeti", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8034, Name = "20. Yüzyılda Osmanlı Devleti", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8035, Name = "I. Dünya Savaşı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8036, Name = "Mondros Ateşkesi, İşgaller ve Cemiyetler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8037, Name = "Kurtuluş Savaşına Hazırlık Dönemi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8038, Name = "I. TBMM Dönemi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8039, Name = "Kurtuluş Savaşı ve Antlaşmalar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8040, Name = "II. TBMM Dönemi ve Çok Partili Hayata Geçiş", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8041, Name = "Türk İnkılabı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8042, Name = "Atatürk İlkeleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8043, Name = "Atatürk Dönemi Türk Dış Politikası", CreatedAt = new DateTime(2025,6,9) },
                        //ayt
                        new { Id = 8044, Name = "Sultan ve Osmanlı Merkez Teşkilatı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8045, Name = "Klasik Çağda Osmanlı Toplum Düzeni", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8046, Name = "Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8047, Name = "Değişim Çağında Avrupa ve Osmanlı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8048, Name = "Uluslararası İlişkilerde Denge Stratejisi (1774-1914)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8049, Name = "Devrimler Çağında Değişen Devlet-Toplum İlişkileri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8050, Name = "Sermaye ve Emek", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8051, Name = "XIX. ve XX. Yüzyılda Değişen Gündelik Hayat", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8052, Name = "XX. Yüzyıl Başlarında Osmanlı Devleti ve Dünya", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8053, Name = "Milli Mücadele", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8054, Name = "Atatürkçülük ve Türk İnkılabı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8055, Name = "İki Savaş Arasındaki Dönemde Türkiye ve Dünya", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8056, Name = "II. Dünya Savaşı Sürecinde Türkiye ve Dünya", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8057, Name = "II. Dünya Savaşı Sonrasında Türkiye ve Dünya", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8058, Name = "Toplumsal Devrim Çağında Dünya ve Türkiye", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 8059, Name = "XXI. Yüzyılın Eşiğinde Türkiye ve Dünya", CreatedAt = new DateTime(2025,6,9) },

                        //turkce
                        new { Id = 9001, Name = "Sözcükte Anlam", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9002, Name = "Sözcükte Anlam - Söz Öbekleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9003, Name = "Söz Sanatları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9004, Name = "Sözcükte Yapı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9005, Name = "Sözcük Türleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9006, Name = "Sözcük Türleri - Ad (İsim)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9007, Name = "Sözcük Türleri - Adıl (Zamir)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9008, Name = "Sözcük Türleri - Önad (Sıfat)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9009, Name = "Sözcük Türleri - Belirteç (Zarf)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9010, Name = "Sözcük Türleri - İlgeç (Edat)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9011, Name = "Sözcük Türleri - Bağlaç", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9012, Name = "Sözcük Türleri - Ünlem", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9013, Name = "Sözcük Türleri - Fiil (Eylem)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9014, Name = "Cümlede Anlam", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9015, Name = "Cümle yorumlama", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9016, Name = "Paragrafta (Parçada) Anlam", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9017, Name = "Paragrafta Anlam - Paragrafın Ana Düşüncesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9018, Name = "Paragrafta Anlam - Paragrafta Yardımcı Düşünceler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9019, Name = "Paragrafta Anlam - Paragrafın Konusu", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9020, Name = "Paragrafta Anlam - Paragrafın Başlığı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9021, Name = "Paragrafta Anlam - Paragrafın Anahtar Kelimesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9022, Name = "Paragrafta Anlam - Paragraf Tamamlama", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9023, Name = "Paragrafta Anlam - Paragrafı İkiye Bölme", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9024, Name = "Paragrafta Anlam - Paragrafın Akışını Bozan Cümle", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9025, Name = "Paragrafta Anlam - Paragrata Anlatım Teknikleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9026, Name = "Paragrafta Anlam - Paragrata Düşünceyi Geliştirme Yolları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9027, Name = "Paragrafta Anlam - Paragrafın Anlatıcı Bakış Açıları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9028, Name = "Yazım Kuralları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9029, Name = "Yazım Kuralları - Büyük Harflerin Yazımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9030, Name = "Yazım Kuralları - Küçük Harf Yazımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9031, Name = "Yazım Kuralları - Kelime ve Söz Gruplarının Yazımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9032, Name = "Yazım Kuralları - Bağlaçların Yazımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9033, Name = "Yazım Kuralları - Kısaltmaların Yazımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9034, Name = "Yazım Kuralları - Sayıların Yazımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9035, Name = "Yazım Kuralları - Yabancı Kelimelerin Yazımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9036, Name = "Yazım Kuralları - Özel İsimlerin Yazımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9037, Name = "Yazım Kuralları - Birleşik Kelimelerin Yazımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9038, Name = "Yazım Kuralları - Bitişik Yazılan Birleşik Kelimeler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9039, Name = "Yazım Kuralları - Ayrı Yazılan Birleşik Kelimeler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9040, Name = "Yazım Kuralları - \"de/da\" Bağlacının Yazımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9041, Name = "Yazım Kuralları - \"ki\" Bağlacının Yazımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9042, Name = "Yazım Kuralları - \"mi\" ” Soru Ekinin Yazımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9043, Name = "Yazım Kuralları - \"ne … ne …\" Bağlacının Yazımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9044, Name = "Yazım Kuralları - Pekiştirmelerin Yazımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9045, Name = "Yazım Kuralları - İkilemelerin Yazımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9046, Name = "Metin Türleri (Edebi Türler)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9047, Name = "Ses Bilgisi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9048, Name = "Ses Bilgisi - Ses Olayları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9049, Name = "Ses Bilgisi - Ünsüz Sertleşmesi (Ünsüz Benzeşmesi)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9050, Name = "Ses Bilgisi - Ünsüz Yumuşaması (Sessiz Yumuşaması)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9051, Name = "Ses Bilgisi - Ses Düşmesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9052, Name = "Ses Bilgisi - Ünlü Düşmesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9053, Name = "Ses Bilgisi - Ünsüz Düşmesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9054, Name = "Ses Bilgisi - Ses Türemesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9055, Name = "Ses Bilgisi - Ünlü Türemesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9056, Name = "Ses Bilgisi - Ünsüz Türemesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9057, Name = "Ses Bilgisi - Ünlü Daralması", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9058, Name = "Ses Bilgisi - Ulama", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9059, Name = "Ses Bilgisi - Kaynaşma", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9060, Name = "Ses Bilgisi - Ünlü Uyumları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9061, Name = "Noktalama İşaretleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9062, Name = "Noktalama İşaretleri - Nokta \".\"", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9063, Name = "Noktalama İşaretleri - Virgül \",\"", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9064, Name = "Noktalama İşaretleri - Noktalı Virgül \";\"", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9065, Name = "Noktalama İşaretleri - İki Nokta \":\"", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9066, Name = "Noktalama İşaretleri - Üç Nokta \"...\"", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9067, Name = "Noktalama İşaretleri - Soru İşareti \"?\"", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9068, Name = "Noktalama İşaretleri - Ünlem İşareti \"!\"", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9069, Name = "Noktalama İşaretleri - Tırnak İşareti \"” “\"", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9070, Name = "Noktalama İşaretleri - Kesme İşareti \"'\"", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9071, Name = "Anlatım Bozuklukları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9072, Name = "Fiilimsiler (Eylemsiler)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9073, Name = "Fiilimsiler (Eylemsiler) - İsim Fiil (Mastar)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9074, Name = "Fiilimsiler (Eylemsiler) - Sıfat Fiil (Ortaç)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9075, Name = "Fiilimsiler (Eylemsiler) - Zarf-Fiil (Ulaç)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9076, Name = "Fiilde (Eylemde) Çatı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9077, Name = "Fiiller", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9078, Name = "Fiiller - Anlamlarına Göre Fiiller", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9079, Name = "Fiiller - Yapılarına Göre Fiiller", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9080, Name = "Fiiller - İş (Kılış) Fiilleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9081, Name = "Fiiller - Durum Fiilleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9082, Name = "Fiiller - Oluş Fiilleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9083, Name = "Fiiller - Basit Fiiller", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9084, Name = "Fiiller - Türemiş Fiiller", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9085, Name = "Fiiller - Birleşik Fiiller", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9086, Name = "Fiiller - Kurallı Birleşik Fiiller", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9087, Name = "Fiiller - Yardımcı Eylemle Kurulan Birleşik Fiiller", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9088, Name = "Fiiller - Anlamca Kaynaşmış Birleşik Fiiller", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9089, Name = "Fiil Çekimi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9090, Name = "Fiil Çekimi - Haber Kipleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9091, Name = "Fiil Çekimi - Dilek Kipleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9092, Name = "Ek Fiil", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9093, Name = "Cümlenin Ögeleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9094, Name = "Cümle Türleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9095, Name = "Sözel Mantık", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9096, Name = "Görsel Okuma", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9097, Name = "Söz Yorumu", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 9098, Name = "Deyimler ve Atasözleri", CreatedAt = new DateTime(2025,6,9) },

                        //turk dili ve edibiyati
                        new { Id = 10001, Name = "Anlam Bilgisi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10002, Name = "Dil Bilgisi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10003, Name = "Güzel Sanatlar ve Edebiyat", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10004, Name = "Metinlerin Sınıflandırılması", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10005, Name = "Şiir Bilgisi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10006, Name = "Edebi Sanatlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10007, Name = "Türk Edebiyatı Dönemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10008, Name = "İslamiyet Öncesi Türk Edebiyatı ve Geçiş Dönemi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10009, Name = "Halk Edebiyatı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10010, Name = "Divan Edebiyatı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10011, Name = "Tanzimat Edebiyatı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10012, Name = "Servet-i Fünun Edebiyatı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10013, Name = "Fecr-i Ati Edebiyatı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10014, Name = "Milli Edebiyat", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10015, Name = "Cumhuriyet Dönemi Edebiyatı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10016, Name = "Edebiyat Akımları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 10017, Name = "Dünya Edebiyatı", CreatedAt = new DateTime(2025,6,9) },

                        //mantik
                        new { Id = 11001, Name = "Mantığa Giriş", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 11002, Name = "Mantığa Giriş", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 11003, Name = "Klasik Mantık", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 11004, Name = "Mantık ve Dil", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 11005, Name = "Sembolik Mantık", CreatedAt = new DateTime(2025,6,9) },

                        //Psikoloji
                        new { Id = 12001, Name = "Psikoloji Bilimini Tanıyalım", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 12002, Name = "Psikolojinin Temel Süreçleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 12003, Name = "Öğrenme Bellek Düşünme", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 12004, Name = "Ruh Sağlığının Temelleri", CreatedAt = new DateTime(2025,6,9) },

                        //Sosyoloji
                        new { Id = 13001, Name = "Sosyolojiye Giriş", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 13002, Name = "Birey ve Toplum", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 13003, Name = "Toplumsal Yapı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 13004, Name = "Toplumsal Değişme ve Gelişme", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 13005, Name = "Toplum ve Kültür", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 13006, Name = "Toplumsal Kurumlar", CreatedAt = new DateTime(2025,6,9) },

                        //Inkılap
                        new { Id = 14001, Name = "Bir Kahraman Doğuyor", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 14002, Name = "Milli Uyanış: Bağımsızlık Yolunda Atılan Adımlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 14003, Name = "Milli Bir Destan: Ya İstiklal, Ya Ölüm", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 14004, Name = "Atatürkçülük ve Çağdaşlaşan Türkiye", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 14005, Name = "Demokratikleşme Çabaları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 14006, Name = "Atatürk Dönemi Dış Politika", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 14007, Name = "Atatürk’ün Ölümü ve Sonrası", CreatedAt = new DateTime(2025,6,9) },

                        //ingilizce
                        new { Id = 15001, Name = "Friendship", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 15002, Name = "Teen Life", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 15003, Name = "In The Kitchen", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 15004, Name = "On The Phone", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 15005, Name = "The Internet", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 15006, Name = "Adventures", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 15007, Name = "Tourism", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 15008, Name = "Chores", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 15009, Name = "Science", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 15010, Name = "Natural Forces", CreatedAt = new DateTime(2025,6,9) },

                        //Fen bilimleri
                        new { Id = 16001, Name = "Mevsimler ve iklimler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 16002, Name = "DNA ve Genetik Kod", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 16003, Name = "Basınç", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 16004, Name = "Madde ve EndüstriPeriyodik Sistem", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 16005, Name = "Fiziksel ve Kimyasal Değişimler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 16006, Name = "Asitler ve Bazlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 16007, Name = "Madde ve Endüstri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 16008, Name = "Basit Makineler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 16009, Name = "Canlılar ve Enerji İlişkileri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 16010, Name = "Enerji Dönüşümleri ve Çevre Bilimi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 16011, Name = "Elektrik Yükleri ve Elektrik Enerjisi", CreatedAt = new DateTime(2025,6,9) },

                        //vatandalik
                        new { Id = 17001, Name = "Hukukun Temel Kavramları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17002, Name = "Hukukun Temel Kavramları - Hukukun Tanımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17003, Name = "Hukukun Temel Kavramları - Hukuk Kaynaklarıyla İlgili Kavramlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17004, Name = "Hukukun Temel Kavramları - Yazısız Kaynaklar (Örf Ve Adet Hukuku)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17005, Name = "Hukukun Temel Kavramları - Yardımcı Kaynaklar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17006, Name = "Hukukun Temel Kavramları - Hukuk Kurallarının Yaptırımları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17007, Name = "Hukukun Temel Kavramları - Kamu Hukuku Dalları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17008, Name = "Hukukun Temel Kavramları - Ceza Ve Ehliyet", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17009, Name = "Hukukun Temel Kavramları - Özel Hukuk Dalları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17010, Name = "Hukukun Temel Kavramları - Hakkın Tanımı Ve Türleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17011, Name = "Devlet Biçimleri Ve Hükümet Sistemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17012, Name = "Devlet Biçimleri Ve Hükümet Sistemleri - Devlet Kavramı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17013, Name = "Devlet Biçimleri Ve Hükümet Sistemleri - Devlet Kurucu Unsurları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17014, Name = "Devlet Biçimleri Ve Hükümet Sistemleri - Devlet Kavramına İlişkin Ayrımlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17015, Name = "Devlet Biçimleri Ve Hükümet Sistemleri - Yapılarına Göre Devlet Şekilleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17016, Name = "Devlet Biçimleri Ve Hükümet Sistemleri - Egemenliğin Kaynağına Göre Devlet Şekilleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17017, Name = "Devlet Biçimleri Ve Hükümet Sistemleri - Hükümet Sistemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17018, Name = "Anayasa Hukukuna Giriş, Temel Kavramlar Ve Türk Anayasa Tarihi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17019, Name = "Anayasa Hukukuna Giriş - Anayasa", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17020, Name = "Anayasa Hukukuna Giriş - Anayasa Kavramına İlişkin Ayrımlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17021, Name = "Anayasa Hukukuna Giriş - Yazılı Anayasa - Yazısız Anayasa Ayrımı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17022, Name = "Anayasa Hukukuna Giriş - Türk Anayasa Tarih", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17023, Name = "Anayasa Hukukuna Giriş - Kanun-U Esasî (1876)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17024, Name = "Anayasa Hukukuna Giriş - Kanun-U Esasî’de 1909 Değişiklikleri (İkinci Meşrutiyet)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17025, Name = "Anayasa Hukukuna Giriş - 1921 Teşkilât-I Esasiye Kanunu", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17026, Name = "Anayasa Hukukuna Giriş - Teşkilat-I Esasiye Kanunu’nda 29 Ekim 1923 Tarihli Değişiklikler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17027, Name = "Anayasa Hukukuna Giriş - 1924 Anayasası", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17028, Name = "Anayasa Hukukuna Giriş - 1961 Anayasası", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17029, Name = "Anayasa Hukukuna Giriş - 1971-1973 Anayasa Değişiklikleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17030, Name = "Anayasa Hukukuna Giriş - 1982 Anayasası", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17031, Name = "Anayasa Hukukuna Giriş - 1982 Anayasasının Temel Özellikleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17032, Name = "Anayasa Hukukuna Giriş - 2017 Anayasasının Temel Özellikleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17033, Name = "Anayasa Hukukuna Giriş - Türk Tarihindeki Referandumlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17034, Name = "Anayasa Hukukuna Giriş - 1982 Anayasası’nın Temel İlkeleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17035, Name = "Yasama", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17036, Name = "Yasama - Yasama Organı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17037, Name = "Yasama - Yasama İşlemleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17038, Name = "Yasama - Tbmm İç Yapı Ve Çalışma Düzeni", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17039, Name = "Yasama - Toplantı Ve Karar Yeter Sayısı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17040, Name = "Yasama - Tbmm Görev Ve Yetkileri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17041, Name = "Yasama - Tbmm Bilgi Edinme Ve Denetim Yolları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17042, Name = "Yürütme", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17043, Name = "Yürütme - Kanun Hükmünde Kararnameler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17044, Name = "Yürütme - Cumhurbaşkanlığı Kararnamesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17045, Name = "Yürütme - Yönetmelik", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17046, Name = "Yürütme - Cumhurbaşkanı’nın Görev Ve Yetkileri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17047, Name = "Yargı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17048, Name = "Yargı - Yargı Organı", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17049, Name = "Yargı - Hakimler Ve Savcılar Kurulu", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17050, Name = "Yargı - Yüksek Mahkemeler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17051, Name = "Yargı - Anayasa Mahkemesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17052, Name = "Yargı - Yargıtay", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17053, Name = "Yargı - Danıştay", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17054, Name = "Yargı - Uyuşmazlık Mahkemesi", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17055, Name = "Yargı - Sayıştay", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17056, Name = "Temel Hak Ve Hürriyetler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17057, Name = "Temel Hak Ve Hürriyetler - Temel Hakların Türleri", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17058, Name = "İdare Hukuku", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17059, Name = "İdare Hukuku - İdare (Kamu Yönetimi)", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17060, Name = "İdare Hukuku - Yerel Yönetim Organları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17061, Name = "İdare Hukuku - Kamu Kuruluşları", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 17062, Name = "İdare Hukuku - Kamu Kuruluşları", CreatedAt = new DateTime(2025,6,9) },
                        //guncel bilgiler
                        new { Id = 18001, Name = "Uluslararası Kuruluşlar Ve Güncel Olaylar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 18002, Name = "Uluslararası Örgüt Ve Kuruluşlar", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 18003, Name = "Kpss Güncel Bilgiler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 18004, Name = "Türkiye’ye Vize Uygulamayan Ülkeler", CreatedAt = new DateTime(2025,6,9) },
                        new { Id = 18005, Name = "Unesco’nun Dünya Mirası Listesindeki Doğal Ve Kültürel Varlıklarımız", CreatedAt = new DateTime(2025,6,9) }
                    ]
                );
        }
    }
}
