using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MySocailApp.Domain.TopicAggregate.Entities;

namespace MySocailApp.Infrastructure.Seeds
{
    public class Topics_Seed : IEntityTypeConfiguration<Topic>
    {
        public void Configure(EntityTypeBuilder<Topic> builder)
        {
            builder
                .HasData(
                    [
                        //matematik
                        //kpss tyt ayt
                        new { Id = 1, Name = "Matematik Temel Kavramlar" },
                        new { Id = 2, Name = "Sayılar" },
                        new { Id = 3, Name = "Sayı Basamakları" },
                        new { Id = 4, Name = "Sayı Kümeleri" },
                        new { Id = 5, Name = "Doğal Sayılar" },
                        new { Id = 6, Name = "Tam Sayılar" },
                        new { Id = 7, Name = "Ondalık Sayılar" },
                        new { Id = 8, Name = "Sayma Sistemleri" },
                        new { Id = 9, Name = "Bölme" },
                        new { Id = 10, Name = "Bölünebilme Kuralları" },
                        new { Id = 11, Name = "EBOB – EKOK" },
                        new { Id = 12, Name = "Asal Çarpanlara Ayırma" },
                        new { Id = 13, Name = "Denklemler" },
                        new { Id = 14, Name = "Rasyonel Sayılar" },
                        new { Id = 15, Name = "Kesir ve Kesir Türleri" },
                        new { Id = 16, Name = "Rasyonel Sayılarda Dört İşlem" },
                        new { Id = 17, Name = "Basit Eşitsizlikler" },
                        new { Id = 18, Name = "Mutlak Değer" },
                        new { Id = 19, Name = "Üslü Sayılar" },
                        new { Id = 20, Name = "Köklü Sayılar" },
                        new { Id = 21, Name = "Çarpanlara Ayırma" },
                        new { Id = 22, Name = "Oran Orantı" },
                        new { Id = 23, Name = "Denklem Çözme" },
                        new { Id = 24, Name = "Problemler" },
                        new { Id = 25, Name = "Sayı Problemleri" },
                        new { Id = 26, Name = "Denklem Kurma Problemleri" },
                        new { Id = 27, Name = "Kesir Problemleri" },
                        new { Id = 28, Name = "Yaş Problemleri" },
                        new { Id = 29, Name = "Havuz Problemleri" },
                        new { Id = 30, Name = "Hareket Hız Problemleri" },
                        new { Id = 31, Name = "İşçi Emek Problemleri" },
                        new { Id = 32, Name = "Yüzde Problemleri" },
                        new { Id = 33, Name = "Kar Zarar Problemleri" },
                        new { Id = 34, Name = "Karışım Problemleri" },
                        new { Id = 35, Name = "Grafik Problemleri" },
                        new { Id = 36, Name = "Rutin Olmayan Problemler" },
                        new { Id = 37, Name = "Kümeler" },
                        new { Id = 38, Name = "Kartezyen Çarpım" },
                        new { Id = 39, Name = "İşlem - Modüler Aritmetik" },
                        new { Id = 40, Name = "Bağıntı ve Fonksiyon" },
                        new { Id = 41, Name = "Faktöriyel" },
                        new { Id = 42, Name = "Permütasyon" },
                        new { Id = 43, Name = "Kombinasyon" },
                        new { Id = 44, Name = "Olasılık" },
                        new { Id = 45, Name = "Tablo ve Grafikler" },
                        new { Id = 46, Name = "Tablo ve Yorumlama" },
                        new { Id = 47, Name = "Grafik ve Yorumlama" },
                        new { Id = 48, Name = "Sayısal Mantık" },
                        //tyt ayt
                        new { Id = 49, Name = "Mantık" },
                        new { Id = 50, Name = "Fonskiyonlar" },
                        new { Id = 51, Name = "Polinomlar" },
                        new { Id = 52, Name = "2.Dereceden Denklemler" },
                        new { Id = 53, Name = "Veri – İstatistik" },
                        //ayt
                        new { Id = 54, Name = "Karmaşık Sayılar" },
                        new { Id = 55, Name = "2.Dereceden Eşitsizlikler" },
                        new { Id = 56, Name = "Parabol" },
                        new { Id = 57, Name = "Trigonometri" },
                        new { Id = 58, Name = "Logaritma" },
                        new { Id = 59, Name = "Diziler" },
                        new { Id = 60, Name = "Limit" },
                        new { Id = 61, Name = "Türev" },
                        new { Id = 62, Name = "İntegral" },
                        //lgs
                        new { Id = 63, Name = "Çarpanlar ve Katlar" },
                        new { Id = 64, Name = "Üslü İfadeler" },
                        new { Id = 65, Name = "Kareköklü İfadeler" },
                        new { Id = 66, Name = "Veri Analizi" },
                        new { Id = 67, Name = "Basit Olayların Olma Olasılığı" },
                        new { Id = 68, Name = "Cebirsel İfadeler ve Özdeşlikler" },
                        new { Id = 69, Name = "Doğrusal Denklemler" },
                        new { Id = 70, Name = "Eşitsizlikler" },
                        new { Id = 71, Name = "Üçgenler" },
                        new { Id = 72, Name = "Eşlik ve Benzerlik" },
                        new { Id = 73, Name = "Geometrik Cisimler" },
                        new { Id = 74, Name = "Dönüşüm Geometrisi" },

                        //Biyoloji
                        new { Id = 1001, Name = "Canlıların Ortak Özellikleri" },
                        new { Id = 1002, Name = "Canlıların Temel Bileşenleri" },
                        new { Id = 1003, Name = "Hücre ve Organeller – Madde Geçişleri" },
                        new { Id = 1004, Name = "Canlıların Sınıflandırılması" },
                        new { Id = 1005, Name = "Hücrede Bölünme – Üreme" },
                        new { Id = 1006, Name = "Kalıtım" },
                        new { Id = 1007, Name = "Bitki Biyolojisi" },
                        new { Id = 1008, Name = "Ekosistem" },
                        new { Id = 1009, Name = "Sinir Sistemi" },
                        new { Id = 1010, Name = "Endokrin Sistem ve Hormonlar" },
                        new { Id = 1011, Name = "Duyu Organları" },
                        new { Id = 1012, Name = "Destek ve Hareket Sistemi" },
                        new { Id = 1013, Name = "Sindirim Sistemi" },
                        new { Id = 1014, Name = "Dolaşım ve Bağışıklık Sistemi" },
                        new { Id = 1015, Name = "Solunum Sistemi" },
                        new { Id = 1016, Name = "Boşaltım Sistemi" },
                        new { Id = 1017, Name = "Üreme Sistemi ve Embriyonik Gelişim" },
                        new { Id = 1018, Name = "Komünite Ekolojisi" },
                        new { Id = 1019, Name = "Popülasyon Ekolojisi" },
                        new { Id = 1020, Name = "Genden Proteine" },
                        new { Id = 1021, Name = "Nükleik Asitler" },
                        new { Id = 1022, Name = "Genetik Şifre ve Protein Sentezi" },
                        new { Id = 1023, Name = "Canlılarda Enerji Dönüşümleri" },
                        new { Id = 1024, Name = "Canlılık ve Enerji" },
                        new { Id = 1025, Name = "Fotosentez" },
                        new { Id = 1026, Name = "Kemosentez" },
                        new { Id = 1027, Name = "Hücresel Solunum" },
                        new { Id = 1028, Name = "Bitki Biyolojisi" },
                        new { Id = 1029, Name = "Canlılar ve Çevre" },

                        //Cografya
                        //kpass
                        new { Id = 2001, Name = "Türkiye'nin Coğrafi Konumu" },
                        new { Id = 2002, Name = "Türkiye'nin Coğrafi Konumu - Matematik (Mutlak) Konum" },
                        new { Id = 2003, Name = "Türkiye'nin Coğrafi Konumu - Türkiye'nin Matematik (Mutlak) Konumu ve Sonuçları" },
                        new { Id = 2004, Name = "Türkiye'nin Coğrafi Konumu - Türkiye'nin Özel (Göreceli) Konumu ve Sonuçları" },
                        new { Id = 2005, Name = "Türkiye'nin Coğrafi Konumu - Türkiye'nin Jeopolitiği" },
                        new { Id = 2006, Name = "Türkiye'nin Yerşekilleri ve Özellikleri" },
                        new { Id = 2007, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'nin Yerşekillerinin Genel Özellikleri" },
                        new { Id = 2008, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Fiziki Haritalar" },
                        new { Id = 2009, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'nin Jeolojik Geçmişi" },
                        new { Id = 2010, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'nin Platoları ve Ovaları" },
                        new { Id = 2011, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'de Dış Güçlerin Oluşturduğu Yer Şekilleri" },
                        new { Id = 2012, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'nin Kıyı Tipleri" },
                        new { Id = 2013, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'de Toprak Oluşumu ve Tipleri" },
                        new { Id = 2014, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'nin Su Varlığı" },
                        new { Id = 2015, Name = "Türkiye'nin Yerşekilleri ve Özellikleri - Türkiye'de Doğal Afetler" },
                        new { Id = 2016, Name = "Türkiye'nin İklimi ve Bitki Örtüsü" },
                        new { Id = 2017, Name = "Türkiye'nin İklimi ve Bitki Örtüsü - Türkiye'nin İklimi" },
                        new { Id = 2018, Name = "Türkiye'nin İklimi ve Bitki Örtüsü - Türkiye'de Sıcaklık" },
                        new { Id = 2019, Name = "Türkiye'nin İklimi ve Bitki Örtüsü - Türkiye'de Nemlilik ve Yağış" },
                        new { Id = 2020, Name = "Türkiye'nin İklimi ve Bitki Örtüsü - Türkiye'de İklim Tipleri" },
                        new { Id = 2021, Name = "Türkiye'nin İklimi ve Bitki Örtüsü - Türkiye'nin Bitki Örtüsü" },
                        new { Id = 2022, Name = "Türkiye'nin İklimi ve Bitki Örtüsü - Türkiye'nin İklim Tipleri ve Bitki Örtüsü" },
                        new { Id = 2023, Name = "Türkiye'de Nüfus ve Yerleşme" },
                        new { Id = 2024, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'de Nüfus Özellikleri" },
                        new { Id = 2025, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'de Nüfusun Dağılışı ve Nüfus Yoğunluğu" },
                        new { Id = 2026, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'nin Nüfusu ve Nüfus Sayımları" },
                        new { Id = 2027, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'nin Nüfus Politikaları" },
                        new { Id = 2028, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'de Nüfus Projeksiyonları: Türkiye Nüfusunun Geleceği" },
                        new { Id = 2029, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'de Göçler" },
                        new { Id = 2030, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'de Yerleşme" },
                        new { Id = 2031, Name = "Türkiye'de Nüfus ve Yerleşme - Türkiye'de Mesken Tipleri" },
                        new { Id = 2032, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık" },
                        new { Id = 2033, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık - Anadolu Uygarlıkları" },
                        new { Id = 2034, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık - Türkiye'de Arazi Kullanımı" },
                        new { Id = 2035, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık - Türkiye Ekonomisinin Sektörel Dağılımı" },
                        new { Id = 2036, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık - Türkiye Ekonomisini Etkileyen Faktörler" },
                        new { Id = 2037, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık - Türkiye'de Tarım" },
                        new { Id = 2038, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık - Türkiye'de Hayvancılık" },
                        new { Id = 2039, Name = "Türkiye'de Tarım, Hayvancılık ve Ormancılık - Türkiye'de Ormancılık" },
                        new { Id = 2040, Name = "Türkiye'de Madenler, Enerji Kaynakları ve Sanayi" },
                        new { Id = 2041, Name = "Türkiye'de Madenler, Enerji Kaynakları ve Sanayi - Türkiye'de Madenler" },
                        new { Id = 2042, Name = "Türkiye'de Madenler, Enerji Kaynakları ve Sanayi - Türkiye'de Enerji Kaynakları" },
                        new { Id = 2043, Name = "Türkiye'de Madenler, Enerji Kaynakları ve Sanayi - Türkiye'de Sanayi" },
                        new { Id = 2044, Name = "Türkiye'de Ulaşım, Ticaret ve Turizm" },
                        new { Id = 2045, Name = "Türkiye'de Ulaşım, Ticaret ve Turizm - Türkiye'de Ulaşım" },
                        new { Id = 2046, Name = "Türkiye'de Ulaşım, Ticaret ve Turizm - Türkiye'de Ticaret" },
                        new { Id = 2047, Name = "Türkiye'de Ulaşım, Ticaret ve Turizm - Türkiye'de Turizm" },
                        new { Id = 2048, Name = "Türkiye'de Ulaşım, Ticaret ve Turizm - Türkiye'nin Millî Parkları Türkiye’de Şehirler ve Özellikleri" },
                        new { Id = 2049, Name = "Türkiye'nin Coğrafi Bölgeleri" },
                        new { Id = 2050, Name = "Türkiye'nin Coğrafi Bölgeleri - Türkiye'de Bölge Sınıflandırması" },
                        new { Id = 2051, Name = "Türkiye'nin Coğrafi Bölgeleri - Türkiye'nin Bölgesel Kalkınma Projeleri" },
                        new { Id = 2052, Name = "Türkiye'nin Coğrafi Bölgeleri - Türkiye'nin Coğrafi Bölgeleri" },
                        new { Id = 2053, Name = "Türkiye'nin Coğrafi Bölgeleri - Karadeniz Bölgesi" },
                        new { Id = 2054, Name = "Türkiye'nin Coğrafi Bölgeleri - Marmara Bölgesi" },
                        new { Id = 2055, Name = "Türkiye'nin Coğrafi Bölgeleri - Ege Bölgesi" },
                        new { Id = 2056, Name = "Türkiye'nin Coğrafi Bölgeleri - Akdeniz Bölgesi" },
                        new { Id = 2057, Name = "Türkiye'nin Coğrafi Bölgeleri - İç Anadolu Bölgesi" },
                        new { Id = 2058, Name = "Türkiye'nin Coğrafi Bölgeleri - Doğu Anadolu Bölgesi" },
                        new { Id = 2059, Name = "Türkiye'nin Coğrafi Bölgeleri - Güneydoğu Anadolu Bölgesi" },
                        new { Id = 2060, Name = "Türkiye'nin Coğrafi Bölgeleri - Bölgelerin Özelliklerinin Karşılaştırılması" },
                        //tyt
                        new { Id = 2061, Name = "Doğa ve İnsan" },
                        new { Id = 2062, Name = "Dünya’nın Şekli ve Hareketleri" },
                        new { Id = 2063, Name = "Coğrafi Konum" },
                        new { Id = 2064, Name = "Harita Bilgisi" },
                        new { Id = 2065, Name = "Atmosfer ve Sıcaklık" },
                        new { Id = 2066, Name = "İklimler" },
                        new { Id = 2067, Name = "Basınç ve Rüzgarlar" },
                        new { Id = 2068, Name = "Nem, Yağış ve Buharlaşma" },
                        new { Id = 2069, Name = "İç Kuvvetler / Dış Kuvvetler" },
                        new { Id = 2070, Name = "Su – Toprak ve Bitkiler" },
                        new { Id = 2071, Name = "Nüfus" },
                        new { Id = 2072, Name = "Göç" },
                        new { Id = 2073, Name = "Yerleşme" },
                        new { Id = 2074, Name = "Türkiye’nin Yer Şekilleri" },
                        new { Id = 2075, Name = "Ekonomik Faaliyetler" },
                        new { Id = 2076, Name = "Bölgeler" },
                        new { Id = 2077, Name = "Uluslararası Ulaşım Hatları" },
                        new { Id = 2078, Name = "Çevre ve Toplum" },
                        new { Id = 2079, Name = "Doğal Afetler" },
                        //ayt
                        new { Id = 2080, Name = "Ekosistem" },
                        new { Id = 2081, Name = "Biyoçeşitlilik" },
                        new { Id = 2082, Name = "Biyomlar" },
                        new { Id = 2083, Name = "Ekosistemin Unsurları" },
                        new { Id = 2084, Name = "Enerji Akışı ve Madde Döngüsü" },
                        new { Id = 2085, Name = "Ekstrem Doğa Olayları" },
                        new { Id = 2086, Name = "Küresel İklim Değişimi" },
                        new { Id = 2087, Name = "Nüfus Politikaları" },
                        new { Id = 2088, Name = "Türkiye'de Nüfus ve Yerleşme" },
                        new { Id = 2089, Name = "Ekonomik Faaliyetler ve Doğal Kaynaklar" },
                        new { Id = 2090, Name = "Göç ve Şehirleşme" },
                        new { Id = 2091, Name = "Türkiye Ekonomisi" },
                        new { Id = 2092, Name = "Türkiye'nin Ekonomi Politikaları" },
                        new { Id = 2093, Name = "Türkiye Ekonomisinin Sektörel Dağılımı" },
                        new { Id = 2094, Name = "Türkiye'de Tarım" },
                        new { Id = 2095, Name = "Türkiye'de Hayvancılık" },
                        new { Id = 2096, Name = "Türkiye'de Madenler ve Enerji Kaynakları" },
                        new { Id = 2097, Name = "Türkiye'de Sanayi" },
                        new { Id = 2098, Name = "Türkiye'de Ulaşım" },
                        new { Id = 2099, Name = "Türkiye'de Ticaret ve Turizm" },
                        new { Id = 2100, Name = "Geçmişten Geleceğe Şehir ve Ekonomi" },
                        new { Id = 2101, Name = "Türkiye'nin İşlevsel Bölgeleri ve Kalkınma Projeleri" },
                        new { Id = 2102, Name = "Hizmet Sektörünün Ekonomideki Yeri" },
                        new { Id = 2103, Name = "Küresel Ticaret" },
                        new { Id = 2104, Name = "Bölgeler ve Ülkeler" },
                        new { Id = 2105, Name = "İlk Uygarlıklar" },
                        new { Id = 2106, Name = "Kültür Bölgeleri ve Türk Kültürü" },
                        new { Id = 2107, Name = "Sanayileşme Süreci: Almanya" },
                        new { Id = 2108, Name = "Tarım ve Ekonomi İlişkisi Fransa – Somali" },
                        new { Id = 2109, Name = "Ülkeler Arası Etkileşim" },
                        new { Id = 2110, Name = "Jeopolitik Konum" },
                        new { Id = 2111, Name = "Çatışma Bölgeleri" },
                        new { Id = 2112, Name = "Küresel ve Bölgesel Örgütler" },
                        new { Id = 2113, Name = "Çevre ve Toplum" },
                        new { Id = 2114, Name = "Çevre Sorunları ve Türleri" },
                        new { Id = 2115, Name = "Madenler ve Enerji Kaynaklarının Çevreye Etkisi" },
                        new { Id = 2116, Name = "Doğal Kaynakların Sürdürülebilir Kullanımı" },
                        new { Id = 2117, Name = "Ekolojik Ayak İzi" },
                        new { Id = 2118, Name = "Doğal Çevrenin Sınırlılığı" },
                        new { Id = 2119, Name = "Çevre Politikaları" },
                        new { Id = 2120, Name = "Çevresel Örgütler" },
                        new { Id = 2121, Name = "Çevre Anlaşmaları" },
                        new { Id = 2122, Name = "Doğal Afetler" },
                        
                        //din kulturu
                        new { Id = 3001, Name = "İnanç" },
                        new { Id = 3002, Name = "İbadet" },
                        new { Id = 3003, Name = "Ahlak ve Değerler" },
                        new { Id = 3004, Name = "Din, Kültür ve Medniyet" },
                        new { Id = 3005, Name = "Hz. Mhammed (S.A.V.)" },
                        new { Id = 3006, Name = "Vahiy ve Akıl" },
                        new { Id = 3007, Name = "Dünya ve Ahiret" },
                        new { Id = 3008, Name = "Kur'an'a göre Hz. Muhammed (S.A.V.)" },
                        new { Id = 3009, Name = "İnançla İlgili Meseleler" },
                        new { Id = 3010, Name = "Yahudilik ve Hristiyanlık" },
                        new { Id = 3011, Name = "İslam ve Bilim" },
                        new { Id = 3012, Name = "Anadolu da İslam" },
                        new { Id = 3013, Name = "İslam Düşüncesinde Tasavvufi Yorumlar" },
                        new { Id = 3014, Name = "Güncel Dini Meseler" },
                        new { Id = 3015, Name = "Hint ve Çin Dinleri" },
                        new { Id = 3016, Name = "Kur'an'da Bazı Kavramlar" },
                        new { Id = 3017, Name = "Kader İnancı" },
                        new { Id = 3018, Name = "Zekat ve Sadaka" },
                        new { Id = 3019, Name = "Din ve Hayat" },
                        new { Id = 3020, Name = "Hz. Muhammed'in Örnekliği" },
                        new { Id = 3021, Name = "Kur'an-ı Kerim ve Özellikleri" },

                        //felsefe
                        new { Id = 4001, Name = "Felsefenin Konusu" },
                        new { Id = 4002, Name = "Bilgi Felsefesi" },
                        new { Id = 4003, Name = "Varlık Felsefesi" },
                        new { Id = 4004, Name = "Din, Kültür ve Medniyet" },
                        new { Id = 4005, Name = "Ahlak Felsefesi" },
                        new { Id = 4006, Name = "Sanat Felsefesi" },
                        new { Id = 4007, Name = "Din Felsefesi" },
                        new { Id = 4008, Name = "Siyaset Felsefesi" },
                        new { Id = 4009, Name = "Bilim Felsefesi" },
                        new { Id = 4010, Name = "İlk Çağ Felsefesi" },
                        new { Id = 4011, Name = "MÖ 6. Yüzyıl – MS 2. Yüzyıl Felsefesi" },
                        new { Id = 4012, Name = "MS 2. Yüzyıl – MS 15. Yüzyıl Felsefesi" },
                        new { Id = 4013, Name = "15. Yüzyıl – 17. Yüzyıl Felsefesi" },
                        new { Id = 4014, Name = "18. Yüzyıl – 19. Yüzyıl Felsefesi" },
                        new { Id = 4015, Name = "20. Yüzyıl Felsefesi" },


                        //fizik
                        new { Id = 5001, Name = "Fizik Bilimine Giriş" },
                        new { Id = 5002, Name = "Madde Ve Özellikleri" },
                        new { Id = 5003, Name = "Kaldırma Kuvveti" },
                        new { Id = 5004, Name = "Basınç" },
                        new { Id = 5005, Name = "Isı, Sıcaklık ve Genleşme" },
                        new { Id = 5006, Name = "Hareket ve Kuvvet" },
                        new { Id = 5007, Name = "Dinamik" },
                        new { Id = 5008, Name = "İş, Güç ve Enerji" },
                        new { Id = 5009, Name = "Elektrostatik" },
                        new { Id = 5010, Name = "Elektrik Akımı ve Devreler" },
                        new { Id = 5011, Name = "Elektriksel Enerji ve Güç" },
                        new { Id = 5012, Name = "Optik" },
                        new { Id = 5013, Name = "Manyetizma" },
                        new { Id = 5014, Name = "Dalgalar" },
                        new { Id = 5015, Name = "Vektörler" },
                        new { Id = 5016, Name = "Kuvvet, Tork ve Denge" },
                        new { Id = 5017, Name = "Kütle Merkezi" },
                        new { Id = 5018, Name = "Basit Makineler" },
                        new { Id = 5019, Name = "Hareket" },
                        new { Id = 5020, Name = "Newton’un Hareket Yasaları" },
                        new { Id = 5021, Name = "İş, Güç ve Enerji II" },
                        new { Id = 5022, Name = "Atışlar" },
                        new { Id = 5023, Name = "İtme ve Momentum" },
                        new { Id = 5024, Name = "Elektrik Alan ve Potansiyel" },
                        new { Id = 5025, Name = "Paralel Levhalar ve Sığa" },
                        new { Id = 5026, Name = "Manyetik Alan ve Manyetik Kuvvet" },
                        new { Id = 5027, Name = "İndüksiyon, Alternatif Akım ve Transformatörler" },
                        new { Id = 5028, Name = "Çembersel Hareket" },
                        new { Id = 5029, Name = "Dönme, Yuvarlanma ve Açısal Momentum" },
                        new { Id = 5030, Name = "Kütle Çekim ve Kepler Yasaları" },
                        new { Id = 5031, Name = "Basit Harmonik Hareket" },
                        new { Id = 5032, Name = "Dalga Mekaniği ve Elektromanyetik Dalgalar" },
                        new { Id = 5033, Name = "Atom Modelleri" },
                        new { Id = 5034, Name = "Büyük Patlama ve Parçacık Fiziği" },
                        new { Id = 5035, Name = "Radyoaktivite" },
                        new { Id = 5036, Name = "Özel Görelilik" },
                        new { Id = 5037, Name = "Kara Cisim Işıması" },
                        new { Id = 5038, Name = "Fotoelektrik Olay ve Compton Olayı" },
                        new { Id = 5039, Name = "Modern Fiziğin Teknolojideki Uygulamaları" },

                        //geometri
                        new { Id = 6001, Name = "Geometrik Kavramlar" },
                        new { Id = 6002, Name = "Doğruda Açılar" },
                        new { Id = 6003, Name = "Üçgende Açılar" },
                        new { Id = 6004, Name = "Üçgende Eşlik ve Benzerlik" },
                        new { Id = 6005, Name = "Özel Üçgenler" },
                        new { Id = 6006, Name = "Dik Üçgen" },
                        new { Id = 6007, Name = "İkizkenar Üçgen" },
                        new { Id = 6008, Name = "Eşkenar Üçgen" },
                        new { Id = 6009, Name = "Açıortay" },
                        new { Id = 6010, Name = "Kenarortay" },
                        new { Id = 6011, Name = "Eşlik ve Benzerlik" },
                        new { Id = 6012, Name = "Üçgende Alan" },
                        new { Id = 6013, Name = "Üçgende Benzerlik" },
                        new { Id = 6014, Name = "Üçgende Açı Kenar Bağıntıları" },
                        new { Id = 6015, Name = "Çokgenler" },
                        new { Id = 6016, Name = "Özel Dörtgenler" },
                        new { Id = 6017, Name = "Dörtgenler" },
                        new { Id = 6018, Name = "Deltoid" },
                        new { Id = 6019, Name = "Paralelkenar" },
                        new { Id = 6020, Name = "Eşkenar Dörtgen" },
                        new { Id = 6021, Name = "Dikdörtgen" },
                        new { Id = 6022, Name = "Kare" },
                        new { Id = 6023, Name = "Yamuk" },
                        new { Id = 6024, Name = "Çember ve Daire" },
                        new { Id = 6025, Name = "Çemberde Açı" },
                        new { Id = 6026, Name = "Çemberde Uzunluk" },
                        new { Id = 6027, Name = "Dairede Çevre ve Alan" },
                        new { Id = 6028, Name = "Analitik Geometri" },
                        new { Id = 6029, Name = "Noktanın Anzalitiği" },
                        new { Id = 6030, Name = "Analitik Düzlem" },
                        new { Id = 6031, Name = "Doğrunun Grafiğinin Çizimi" },
                        new { Id = 6032, Name = "Doğrunun Denklemleri" },
                        new { Id = 6033, Name = "Doğrunun Analitiği" },
                        new { Id = 6034, Name = "Simetriler" },
                        new { Id = 6035, Name = "Eşitsizlikler" },
                        new { Id = 6036, Name = "Dönüşüm Geometrisi" },
                        new { Id = 6037, Name = "Katı Cisimler" },
                        new { Id = 6038, Name = "Prizmalar" },
                        new { Id = 6039, Name = "Dikdörtgenler Prizmalar" },
                        new { Id = 6040, Name = "Küp" },
                        new { Id = 6041, Name = "Silindir" },
                        new { Id = 6042, Name = "Dönel Silindir" },
                        new { Id = 6043, Name = "Kesik Piramit" },
                        new { Id = 6044, Name = "Piramit" },
                        new { Id = 6045, Name = "Koni" },
                        new { Id = 6046, Name = "Küre" },
                        new { Id = 6047, Name = "Çemberin Analitiği" },

                        //kimya
                        new { Id = 7001, Name = "Kimya Bilimi" },
                        new { Id = 7002, Name = "Atom ve Yapısı" },
                        new { Id = 7003, Name = "Periyodik Sistem" },
                        new { Id = 7004, Name = "Kimyasal Türler Arası Etkileşimler" },
                        new { Id = 7005, Name = "Maddenin Halleri" },
                        new { Id = 7006, Name = "Kimyanın Temel Kanunları" },
                        new { Id = 7007, Name = "Asitler, Bazlar ve Tuzlar" },
                        new { Id = 7008, Name = "Kimyasal Hesaplamalar" },
                        new { Id = 7009, Name = "Karışımlar" },
                        new { Id = 7010, Name = "Endüstride ve Canlılarda Enerji" },
                        new { Id = 7011, Name = "Kimya Her Yerde" },
                        new { Id = 7012, Name = "Modern Atom Teorisi." },
                        new { Id = 7013, Name = "Gazlar" },
                        new { Id = 7014, Name = "Sıvı Çözeltiler ve Çözünürlük." },
                        new { Id = 7015, Name = "Kimyasal Tepkimelerde Enerji" },
                        new { Id = 7016, Name = "Kimyasal Tepkimelerde Hız" },
                        new { Id = 7017, Name = "Kimyasal Tepkimelerde Denge" },
                        new { Id = 7018, Name = "Asit-Baz Dengesi" },
                        new { Id = 7019, Name = "Çözünürlük Dengesi" },
                        new { Id = 7020, Name = "Kimya ve Elektrik" },
                        new { Id = 7021, Name = "Organik Kimyaya Giriş" },
                        new { Id = 7022, Name = "Organik Kimya" },
                        new { Id = 7023, Name = "Hidrokarbonlar" },
                        new { Id = 7024, Name = "Fonksiyonel Gruplar" },
                        new { Id = 7025, Name = "Enerji Kaynakları ve Bilimsel Gelişmeler" },

                        //tarih
                        //kpss
                        new { Id = 8001, Name = "İslamiyet Öncesi Türk Tarihi" },
                        new { Id = 8002, Name = "İlk Türk - İslam Devletleri ve Beylikleri" },
                        new { Id = 8003, Name = "Osmanlı Devleti Kuruluş ve Yükselme Dönemleri" },
                        new { Id = 8004, Name = "Osmanlı Devleti’nde Kültür ve Uygarlık" },
                        new { Id = 8005, Name = "XVII. Yüzyılda Osmanlı Devleti (Duraklama Dönemi)" },
                        new { Id = 8006, Name = "XVIII. Yüzyılda Osmanlı Devleti (Gerileme Dönemi)" },
                        new { Id = 8007, Name = "XIX. Yüzyılda Osmanlı Devleti (Dağılma Dönemi)" },
                        new { Id = 8008, Name = "XX. Yüzyılda Osmanlı Devleti" },
                        new { Id = 8009, Name = "Kurtuluş Savaşı Hazırlık Dönemi" },
                        new { Id = 8010, Name = "I. TBMM Dönemi" },
                        new { Id = 8011, Name = "Kurtuluş Savaşı Muharebeler Dönemi" },
                        new { Id = 8012, Name = "Atatürk İnkılapları" },
                        new { Id = 8013, Name = "Atatürk İlkeleri" },
                        new { Id = 8014, Name = "Partiler ve Partileşme Dönemi (İç Politika)" },
                        new { Id = 8015, Name = "Atatürk Dönemi Türk Dış Politikası" },
                        new { Id = 8016, Name = "Atatürk Sonrası Dönem" },
                        new { Id = 8017, Name = "Atatürk’ün Hayatı ve Kişiliği" },
                        //tyt + ayt
                        new { Id = 8018, Name = "Tarih ve Zaman" },
                        new { Id = 8019, Name = "İnsanlığın İlk Dönemleri" },
                        new { Id = 8020, Name = "Ortaçağ’da Dünya" },
                        new { Id = 8021, Name = "İlk ve Orta Çağlarda Türk Dünyası" },
                        new { Id = 8022, Name = "İslam Medeniyetinin Doğuşu" },
                        new { Id = 8023, Name = "Türklerin İslamiyet’i Kabulü ve İlk Türk İslam Devletleri" },
                        new { Id = 8024, Name = "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi" },
                        new { Id = 8025, Name = "Beylikten Devlete Osmanlı Siyaseti" },
                        new { Id = 8026, Name = "Devletleşme Sürecinde Savaşçılar ve Askerler" },
                        new { Id = 8027, Name = "Dünya Gücü Osmanlı Devleti" },
                        //tyt
                        new { Id = 8028, Name = "Yeni Çağ Avrupa Tarihi" },
                        new { Id = 8029, Name = "Yakın Çağ Avrupa Tarihi" },
                        new { Id = 8030, Name = "Osmanlı Devletinde Arayış Yılları" },
                        new { Id = 8031, Name = "18. Yüzyılda Değişim ve Diplomasi" },
                        new { Id = 8032, Name = "En Uzun Yüzyıl" },
                        new { Id = 8033, Name = "Osmanlı Kültür ve Medeniyeti" },
                        new { Id = 8034, Name = "20. Yüzyılda Osmanlı Devleti" },
                        new { Id = 8035, Name = "I. Dünya Savaşı" },
                        new { Id = 8036, Name = "Mondros Ateşkesi, İşgaller ve Cemiyetler" },
                        new { Id = 8037, Name = "Kurtuluş Savaşına Hazırlık Dönemi" },
                        new { Id = 8038, Name = "I. TBMM Dönemi" },
                        new { Id = 8039, Name = "Kurtuluş Savaşı ve Antlaşmalar" },
                        new { Id = 8040, Name = "II. TBMM Dönemi ve Çok Partili Hayata Geçiş" },
                        new { Id = 8041, Name = "Türk İnkılabı" },
                        new { Id = 8042, Name = "Atatürk İlkeleri" },
                        new { Id = 8043, Name = "Atatürk Dönemi Türk Dış Politikası" },
                        //ayt
                        new { Id = 8044, Name = "Sultan ve Osmanlı Merkez Teşkilatı" },
                        new { Id = 8045, Name = "Klasik Çağda Osmanlı Toplum Düzeni" },
                        new { Id = 8046, Name = "Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti" },
                        new { Id = 8047, Name = "Değişim Çağında Avrupa ve Osmanlı" },
                        new { Id = 8048, Name = "Uluslararası İlişkilerde Denge Stratejisi (1774-1914)" },
                        new { Id = 8049, Name = "Devrimler Çağında Değişen Devlet-Toplum İlişkileri" },
                        new { Id = 8050, Name = "Sermaye ve Emek" },
                        new { Id = 8051, Name = "XIX. ve XX. Yüzyılda Değişen Gündelik Hayat" },
                        new { Id = 8052, Name = "XX. Yüzyıl Başlarında Osmanlı Devleti ve Dünya" },
                        new { Id = 8053, Name = "Milli Mücadele" },
                        new { Id = 8054, Name = "Atatürkçülük ve Türk İnkılabı" },
                        new { Id = 8055, Name = "İki Savaş Arasındaki Dönemde Türkiye ve Dünya" },
                        new { Id = 8056, Name = "II. Dünya Savaşı Sürecinde Türkiye ve Dünya" },
                        new { Id = 8057, Name = "II. Dünya Savaşı Sonrasında Türkiye ve Dünya" },
                        new { Id = 8058, Name = "Toplumsal Devrim Çağında Dünya ve Türkiye" },
                        new { Id = 8059, Name = "XXI. Yüzyılın Eşiğinde Türkiye ve Dünya" },

                        //turkce
                        new { Id = 9001, Name = "Sözcükte Anlam" },
                        new { Id = 9002, Name = "Sözcükte Anlam - Söz Öbekleri" },
                        new { Id = 9003, Name = "Söz Sanatları" },
                        new { Id = 9004, Name = "Sözcükte Yapı" },
                        new { Id = 9005, Name = "Sözcük Türleri" },
                        new { Id = 9006, Name = "Sözcük Türleri - Ad (İsim)" },
                        new { Id = 9007, Name = "Sözcük Türleri - Adıl (Zamir)" },
                        new { Id = 9008, Name = "Sözcük Türleri - Önad (Sıfat)" },
                        new { Id = 9009, Name = "Sözcük Türleri - Belirteç (Zarf)" },
                        new { Id = 9010, Name = "Sözcük Türleri - İlgeç (Edat)" },
                        new { Id = 9011, Name = "Sözcük Türleri - Bağlaç" },
                        new { Id = 9012, Name = "Sözcük Türleri - Ünlem" },
                        new { Id = 9013, Name = "Sözcük Türleri - Fiil (Eylem)" },
                        new { Id = 9014, Name = "Cümlede Anlam" },
                        new { Id = 9015, Name = "Cümle yorumlama"},
                        new { Id = 9016, Name = "Paragrafta (Parçada) Anlam" },
                        new { Id = 9017, Name = "Paragrafta Anlam - Paragrafın Ana Düşüncesi" },
                        new { Id = 9018, Name = "Paragrafta Anlam - Paragrafta Yardımcı Düşünceler" },
                        new { Id = 9019, Name = "Paragrafta Anlam - Paragrafın Konusu" },
                        new { Id = 9020, Name = "Paragrafta Anlam - Paragrafın Başlığı" },
                        new { Id = 9021, Name = "Paragrafta Anlam - Paragrafın Anahtar Kelimesi" },
                        new { Id = 9022, Name = "Paragrafta Anlam - Paragraf Tamamlama" },
                        new { Id = 9023, Name = "Paragrafta Anlam - Paragrafı İkiye Bölme" },
                        new { Id = 9024, Name = "Paragrafta Anlam - Paragrafın Akışını Bozan Cümle" },
                        new { Id = 9025, Name = "Paragrafta Anlam - Paragrata Anlatım Teknikleri" },
                        new { Id = 9026, Name = "Paragrafta Anlam - Paragrata Düşünceyi Geliştirme Yolları" },
                        new { Id = 9027, Name = "Paragrafta Anlam - Paragrafın Anlatıcı Bakış Açıları" },
                        new { Id = 9028, Name = "Yazım Kuralları" },
                        new { Id = 9029, Name = "Yazım Kuralları - Büyük Harflerin Yazımı" },
                        new { Id = 9030, Name = "Yazım Kuralları - Küçük Harf Yazımı" },
                        new { Id = 9031, Name = "Yazım Kuralları - Kelime ve Söz Gruplarının Yazımı" },
                        new { Id = 9032, Name = "Yazım Kuralları - Bağlaçların Yazımı" },
                        new { Id = 9033, Name = "Yazım Kuralları - Kısaltmaların Yazımı" },
                        new { Id = 9034, Name = "Yazım Kuralları - Sayıların Yazımı" },
                        new { Id = 9035, Name = "Yazım Kuralları - Yabancı Kelimelerin Yazımı" },
                        new { Id = 9036, Name = "Yazım Kuralları - Özel İsimlerin Yazımı" },
                        new { Id = 9037, Name = "Yazım Kuralları - Birleşik Kelimelerin Yazımı" },
                        new { Id = 9038, Name = "Yazım Kuralları - Bitişik Yazılan Birleşik Kelimeler" },
                        new { Id = 9039, Name = "Yazım Kuralları - Ayrı Yazılan Birleşik Kelimeler" },
                        new { Id = 9040, Name = "Yazım Kuralları - \"de/da\" Bağlacının Yazımı" },
                        new { Id = 9041, Name = "Yazım Kuralları - \"ki\" Bağlacının Yazımı" },
                        new { Id = 9042, Name = "Yazım Kuralları - \"mi\" ” Soru Ekinin Yazımı" },
                        new { Id = 9043, Name = "Yazım Kuralları - \"ne … ne …\" Bağlacının Yazımı" },
                        new { Id = 9044, Name = "Yazım Kuralları - Pekiştirmelerin Yazımı" },
                        new { Id = 9045, Name = "Yazım Kuralları - İkilemelerin Yazımı" },
                        new { Id = 9046, Name = "Metin Türleri (Edebi Türler)"},
                        new { Id = 9047, Name = "Ses Bilgisi" },
                        new { Id = 9048, Name = "Ses Bilgisi - Ses Olayları" },
                        new { Id = 9049, Name = "Ses Bilgisi - Ünsüz Sertleşmesi (Ünsüz Benzeşmesi)" },
                        new { Id = 9050, Name = "Ses Bilgisi - Ünsüz Yumuşaması (Sessiz Yumuşaması)" },
                        new { Id = 9051, Name = "Ses Bilgisi - Ses Düşmesi" },
                        new { Id = 9052, Name = "Ses Bilgisi - Ünlü Düşmesi" },
                        new { Id = 9053, Name = "Ses Bilgisi - Ünsüz Düşmesi" },
                        new { Id = 9054, Name = "Ses Bilgisi - Ses Türemesi" },
                        new { Id = 9055, Name = "Ses Bilgisi - Ünlü Türemesi" },
                        new { Id = 9056, Name = "Ses Bilgisi - Ünsüz Türemesi" },
                        new { Id = 9057, Name = "Ses Bilgisi - Ünlü Daralması" },
                        new { Id = 9058, Name = "Ses Bilgisi - Ulama" },
                        new { Id = 9059, Name = "Ses Bilgisi - Kaynaşma" },
                        new { Id = 9060, Name = "Ses Bilgisi - Ünlü Uyumları" },
                        new { Id = 9061, Name = "Noktalama İşaretleri" },
                        new { Id = 9062, Name = "Noktalama İşaretleri - Nokta \".\"" },
                        new { Id = 9063, Name = "Noktalama İşaretleri - Virgül \",\"" },
                        new { Id = 9064, Name = "Noktalama İşaretleri - Noktalı Virgül \";\"" },
                        new { Id = 9065, Name = "Noktalama İşaretleri - İki Nokta \":\"" },
                        new { Id = 9066, Name = "Noktalama İşaretleri - Üç Nokta \"...\"" },
                        new { Id = 9067, Name = "Noktalama İşaretleri - Soru İşareti \"?\"" },
                        new { Id = 9068, Name = "Noktalama İşaretleri - Ünlem İşareti \"!\"" },
                        new { Id = 9069, Name = "Noktalama İşaretleri - Tırnak İşareti \"” “\"" },
                        new { Id = 9070, Name = "Noktalama İşaretleri - Kesme İşareti \"'\"" },
                        new { Id = 9071, Name = "Anlatım Bozuklukları" },
                        new { Id = 9072, Name = "Fiilimsiler (Eylemsiler)" },
                        new { Id = 9073, Name = "Fiilimsiler (Eylemsiler) - İsim Fiil (Mastar)" },
                        new { Id = 9074, Name = "Fiilimsiler (Eylemsiler) - Sıfat Fiil (Ortaç)" },
                        new { Id = 9075, Name = "Fiilimsiler (Eylemsiler) - Zarf-Fiil (Ulaç)" },
                        new { Id = 9076, Name = "Fiilde (Eylemde) Çatı" },
                        new { Id = 9077, Name = "Fiiller" },
                        new { Id = 9078, Name = "Fiiller - Anlamlarına Göre Fiiller" },
                        new { Id = 9079, Name = "Fiiller - Yapılarına Göre Fiiller" },
                        new { Id = 9080, Name = "Fiiller - İş (Kılış) Fiilleri" },
                        new { Id = 9081, Name = "Fiiller - Durum Fiilleri" },
                        new { Id = 9082, Name = "Fiiller - Oluş Fiilleri" },
                        new { Id = 9083, Name = "Fiiller - Basit Fiiller" },
                        new { Id = 9084, Name = "Fiiller - Türemiş Fiiller" },
                        new { Id = 9085, Name = "Fiiller - Birleşik Fiiller" },
                        new { Id = 9086, Name = "Fiiller - Kurallı Birleşik Fiiller" },
                        new { Id = 9087, Name = "Fiiller - Yardımcı Eylemle Kurulan Birleşik Fiiller" },
                        new { Id = 9088, Name = "Fiiller - Anlamca Kaynaşmış Birleşik Fiiller" },
                        new { Id = 9089, Name = "Fiil Çekimi" },
                        new { Id = 9090, Name = "Fiil Çekimi - Haber Kipleri" },
                        new { Id = 9091, Name = "Fiil Çekimi - Dilek Kipleri" },
                        new { Id = 9092, Name = "Ek Fiil" },
                        new { Id = 9093, Name = "Cümlenin Ögeleri" },
                        new { Id = 9094, Name = "Cümle Türleri" },
                        new { Id = 9095, Name = "Sözel Mantık" },
                        new { Id = 9096, Name = "Görsel Okuma" },
                        new { Id = 9097, Name = "Söz Yorumu" },
                        new { Id = 9098, Name = "Deyimler ve Atasözleri" },

                        //turk dili ve edibiyati
                        new { Id = 10001, Name = "Anlam Bilgisi" },
                        new { Id = 10002, Name = "Dil Bilgisi" },
                        new { Id = 10003, Name = "Güzel Sanatlar ve Edebiyat" },
                        new { Id = 10004, Name = "Metinlerin Sınıflandırılması" },
                        new { Id = 10005, Name = "Şiir Bilgisi" },
                        new { Id = 10006, Name = "Edebi Sanatlar" },
                        new { Id = 10007, Name = "Türk Edebiyatı Dönemleri" },
                        new { Id = 10008, Name = "İslamiyet Öncesi Türk Edebiyatı ve Geçiş Dönemi" },
                        new { Id = 10009, Name = "Halk Edebiyatı" },
                        new { Id = 10010, Name = "Divan Edebiyatı" },
                        new { Id = 10011, Name = "Tanzimat Edebiyatı" },
                        new { Id = 10012, Name = "Servet-i Fünun Edebiyatı" },
                        new { Id = 10013, Name = "Fecr-i Ati Edebiyatı" },
                        new { Id = 10014, Name = "Milli Edebiyat" },
                        new { Id = 10015, Name = "Cumhuriyet Dönemi Edebiyatı" },
                        new { Id = 10016, Name = "Edebiyat Akımları" },
                        new { Id = 10017, Name = "Dünya Edebiyatı" },

                        //mantik
                        new { Id = 11001, Name = "Mantığa Giriş" },
                        new { Id = 11002, Name = "Mantığa Giriş" },
                        new { Id = 11003, Name = "Klasik Mantık" },
                        new { Id = 11004, Name = "Mantık ve Dil" },
                        new { Id = 11005, Name = "Sembolik Mantık" },

                        //Psikoloji
                        new { Id = 12001, Name = "Psikoloji Bilimini Tanıyalım" },
                        new { Id = 12002, Name = "Psikolojinin Temel Süreçleri" },
                        new { Id = 12003, Name = "Öğrenme Bellek Düşünme" },
                        new { Id = 12004, Name = "Ruh Sağlığının Temelleri" },

                        //Sosyoloji
                        new { Id = 13001, Name = "Sosyolojiye Giriş" },
                        new { Id = 13002, Name = "Birey ve Toplum" },
                        new { Id = 13003, Name = "Toplumsal Yapı" },
                        new { Id = 13004, Name = "Toplumsal Değişme ve Gelişme" },
                        new { Id = 13005, Name = "Toplum ve Kültür" },
                        new { Id = 13006, Name = "Toplumsal Kurumlar" },

                        //Inkılap
                        new { Id = 14001, Name = "Bir Kahraman Doğuyor" },
                        new { Id = 14002, Name = "Milli Uyanış: Bağımsızlık Yolunda Atılan Adımlar" },
                        new { Id = 14003, Name = "Milli Bir Destan: Ya İstiklal, Ya Ölüm" },
                        new { Id = 14004, Name = "Atatürkçülük ve Çağdaşlaşan Türkiye" },
                        new { Id = 14005, Name = "Demokratikleşme Çabaları" },
                        new { Id = 14006, Name = "Atatürk Dönemi Dış Politika" },
                        new { Id = 14007, Name = "Atatürk’ün Ölümü ve Sonrası" },

                        //ingilizce
                        new { Id = 15001, Name = "Friendship" },
                        new { Id = 15002, Name = "Teen Life" },
                        new { Id = 15003, Name = "In The Kitchen" },
                        new { Id = 15004, Name = "On The Phone" },
                        new { Id = 15005, Name = "The Internet" },
                        new { Id = 15006, Name = "Adventures" },
                        new { Id = 15007, Name = "Tourism" },
                        new { Id = 15008, Name = "Chores" },
                        new { Id = 15009, Name = "Science" },
                        new { Id = 15010, Name = "Natural Forces" },

                        //Fen bilimleri
                        new { Id = 16001, Name = "Mevsimler ve iklimler" },
                        new { Id = 16002, Name = "DNA ve Genetik Kod" },
                        new { Id = 16003, Name = "Basınç" },
                        new { Id = 16004, Name = "Madde ve EndüstriPeriyodik Sistem" },
                        new { Id = 16005, Name = "Fiziksel ve Kimyasal Değişimler" },
                        new { Id = 16006, Name = "Asitler ve Bazlar" },
                        new { Id = 16007, Name = "Madde ve Endüstri" },
                        new { Id = 16008, Name = "Basit Makineler" },
                        new { Id = 16009, Name = "Canlılar ve Enerji İlişkileri" },
                        new { Id = 16010, Name = "Enerji Dönüşümleri ve Çevre Bilimi" },
                        new { Id = 16011, Name = "Elektrik Yükleri ve Elektrik Enerjisi" },

                        //vatandalik
                        new { Id = 17001, Name = "Hukukun Temel Kavramları" },
                        new { Id = 17002, Name = "Hukukun Temel Kavramları - Hukukun Tanımı" },
                        new { Id = 17003, Name = "Hukukun Temel Kavramları - Hukuk Kaynaklarıyla İlgili Kavramlar" },
                        new { Id = 17004, Name = "Hukukun Temel Kavramları - Yazısız Kaynaklar (Örf Ve Adet Hukuku)" },
                        new { Id = 17005, Name = "Hukukun Temel Kavramları - Yardımcı Kaynaklar" },
                        new { Id = 17006, Name = "Hukukun Temel Kavramları - Hukuk Kurallarının Yaptırımları" },
                        new { Id = 17007, Name = "Hukukun Temel Kavramları - Kamu Hukuku Dalları" },
                        new { Id = 17008, Name = "Hukukun Temel Kavramları - Ceza Ve Ehliyet" },
                        new { Id = 17009, Name = "Hukukun Temel Kavramları - Özel Hukuk Dalları" },
                        new { Id = 17010, Name = "Hukukun Temel Kavramları - Hakkın Tanımı Ve Türleri" },
                        new { Id = 17011, Name = "Devlet Biçimleri Ve Hükümet Sistemleri" },
                        new { Id = 17012, Name = "Devlet Biçimleri Ve Hükümet Sistemleri - Devlet Kavramı" },
                        new { Id = 17013, Name = "Devlet Biçimleri Ve Hükümet Sistemleri - Devlet Kurucu Unsurları" },
                        new { Id = 17014, Name = "Devlet Biçimleri Ve Hükümet Sistemleri - Devlet Kavramına İlişkin Ayrımlar" },
                        new { Id = 17015, Name = "Devlet Biçimleri Ve Hükümet Sistemleri - Yapılarına Göre Devlet Şekilleri" },
                        new { Id = 17016, Name = "Devlet Biçimleri Ve Hükümet Sistemleri - Egemenliğin Kaynağına Göre Devlet Şekilleri" },
                        new { Id = 17017, Name = "Devlet Biçimleri Ve Hükümet Sistemleri - Hükümet Sistemleri" },
                        new { Id = 17018, Name = "Anayasa Hukukuna Giriş, Temel Kavramlar Ve Türk Anayasa Tarihi" },
                        new { Id = 17019, Name = "Anayasa Hukukuna Giriş - Anayasa" },
                        new { Id = 17020, Name = "Anayasa Hukukuna Giriş - Anayasa Kavramına İlişkin Ayrımlar" },
                        new { Id = 17021, Name = "Anayasa Hukukuna Giriş - Yazılı Anayasa - Yazısız Anayasa Ayrımı" },
                        new { Id = 17022, Name = "Anayasa Hukukuna Giriş - Türk Anayasa Tarih" },
                        new { Id = 17023, Name = "Anayasa Hukukuna Giriş - Kanun-U Esasî (1876)" },
                        new { Id = 17024, Name = "Anayasa Hukukuna Giriş - Kanun-U Esasî’de 1909 Değişiklikleri (İkinci Meşrutiyet)" },
                        new { Id = 17025, Name = "Anayasa Hukukuna Giriş - 1921 Teşkilât-I Esasiye Kanunu" },
                        new { Id = 17026, Name = "Anayasa Hukukuna Giriş - Teşkilat-I Esasiye Kanunu’nda 29 Ekim 1923 Tarihli Değişiklikler" },
                        new { Id = 17027, Name = "Anayasa Hukukuna Giriş - 1924 Anayasası" },
                        new { Id = 17028, Name = "Anayasa Hukukuna Giriş - 1961 Anayasası" },
                        new { Id = 17029, Name = "Anayasa Hukukuna Giriş - 1971-1973 Anayasa Değişiklikleri" },
                        new { Id = 17030, Name = "Anayasa Hukukuna Giriş - 1982 Anayasası" },
                        new { Id = 17031, Name = "Anayasa Hukukuna Giriş - 1982 Anayasasının Temel Özellikleri" },
                        new { Id = 17032, Name = "Anayasa Hukukuna Giriş - 2017 Anayasasının Temel Özellikleri" },
                        new { Id = 17033, Name = "Anayasa Hukukuna Giriş - Türk Tarihindeki Referandumlar" },
                        new { Id = 17034, Name = "Anayasa Hukukuna Giriş - 1982 Anayasası’nın Temel İlkeleri" },
                        new { Id = 17035, Name = "Yasama" },
                        new { Id = 17036, Name = "Yasama - Yasama Organı" },
                        new { Id = 17037, Name = "Yasama - Yasama İşlemleri" },
                        new { Id = 17038, Name = "Yasama - Tbmm İç Yapı Ve Çalışma Düzeni" },
                        new { Id = 17039, Name = "Yasama - Toplantı Ve Karar Yeter Sayısı" },
                        new { Id = 17040, Name = "Yasama - Tbmm Görev Ve Yetkileri" },
                        new { Id = 17041, Name = "Yasama - Tbmm Bilgi Edinme Ve Denetim Yolları" },
                        new { Id = 17042, Name = "Yürütme" },
                        new { Id = 17043, Name = "Yürütme - Kanun Hükmünde Kararnameler" },
                        new { Id = 17044, Name = "Yürütme - Cumhurbaşkanlığı Kararnamesi" },
                        new { Id = 17045, Name = "Yürütme - Yönetmelik" },
                        new { Id = 17046, Name = "Yürütme - Cumhurbaşkanı’nın Görev Ve Yetkileri" },
                        new { Id = 17047, Name = "Yargı" },
                        new { Id = 17048, Name = "Yargı - Yargı Organı" },
                        new { Id = 17049, Name = "Yargı - Hakimler Ve Savcılar Kurulu" },
                        new { Id = 17050, Name = "Yargı - Yüksek Mahkemeler" },
                        new { Id = 17051, Name = "Yargı - Anayasa Mahkemesi" },
                        new { Id = 17052, Name = "Yargı - Yargıtay" },
                        new { Id = 17053, Name = "Yargı - Danıştay" },
                        new { Id = 17054, Name = "Yargı - Uyuşmazlık Mahkemesi" },
                        new { Id = 17055, Name = "Yargı - Sayıştay" },
                        new { Id = 17056, Name = "Temel Hak Ve Hürriyetler" },
                        new { Id = 17057, Name = "Temel Hak Ve Hürriyetler - Temel Hakların Türleri" },
                        new { Id = 17058, Name = "İdare Hukuku" },
                        new { Id = 17059, Name = "İdare Hukuku - İdare (Kamu Yönetimi)" },
                        new { Id = 17060, Name = "İdare Hukuku - Yerel Yönetim Organları" },
                        new { Id = 17061, Name = "İdare Hukuku - Kamu Kuruluşları" },
                        new { Id = 17062, Name = "İdare Hukuku - Kamu Kuruluşları" },
                        //guncel bilgiler
                        new { Id = 18001, Name = "Uluslararası Kuruluşlar Ve Güncel Olaylar" },
                        new { Id = 18002, Name = "Uluslararası Örgüt Ve Kuruluşlar" },
                        new { Id = 18003, Name = "Kpss Güncel Bilgiler" },
                        new { Id = 18004, Name = "Türkiye’ye Vize Uygulamayan Ülkeler" },
                        new { Id = 18005, Name = "Unesco’nun Dünya Mirası Listesindeki Doğal Ve Kültürel Varlıklarımız" }
                    ]
                );
        }
    }
}
